# Generated by Django 3.2.8 on 2022-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0003_auto_20220228_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opexauxiliatefactor',
            name='salvage_calculated',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
