# Generated by Django 3.2.8 on 2022-03-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0004_alter_opexauxiliatefactor_salvage_calculated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opexauxiliatefactor',
            old_name='fci',
            new_name='fcil',
        ),
    ]
