# Generated by Django 3.2.8 on 2022-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0005_rename_fci_opexauxiliatefactor_fcil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
