# Generated by Django 3.2.8 on 2022-03-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0002_auto_20220228_2209'),
        ('opex', '0006_materialcosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcosts',
            name='classification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='materialcosts',
            name='flow',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='materialcosts',
            name='flow_unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_costs', to='capex.equipmentunity'),
        ),
        migrations.AddField(
            model_name='materialcosts',
            name='material_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capex.equipmentunity'),
        ),
        migrations.AddField(
            model_name='materialcosts',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterModelTable(
            name='materialcosts',
            table='opex_materials',
        ),
    ]
