# Generated by Django 3.2.8 on 2022-03-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0003_auto_20220301_1449'),
        ('opex', '0007_auto_20220301_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentsUtilitiesConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('classification', models.CharField(blank=True, max_length=300, null=True)),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_costs', to='capex.equipmentunity')),
            ],
            options={
                'db_table': 'utilities_constants',
            },
        ),
        migrations.CreateModel(
            name='EquipmentsUtilitiesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('duty', models.FloatField(blank=True, default=0, null=True)),
                ('classification', models.CharField(blank=True, max_length=300, null=True)),
                ('cost_unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_unity_utilities', to='capex.equipmentunity')),
                ('duty_unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capex.equipmentunity')),
                ('purchased_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.equipmentproject')),
            ],
            options={
                'db_table': 'utilities_settings',
            },
        ),
        migrations.CreateModel(
            name='OpexProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex_source', models.CharField(blank=True, max_length=25, null=True)),
                ('revenue_calculated', models.BooleanField(blank=True, default=True)),
                ('crm_calculated', models.BooleanField(blank=True, default=True)),
                ('salvage_calculated', models.BooleanField(blank=True, default=True)),
                ('cut_calculated', models.BooleanField(blank=True, default=True)),
                ('wc_calculated', models.BooleanField(blank=True, default=True)),
                ('col_calculated', models.BooleanField(blank=True, default=True)),
                ('cwt_calculated', models.BooleanField(blank=True, default=True)),
                ('construction_period', models.IntegerField(blank=True, default=0, null=True)),
                ('project_life', models.IntegerField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.capexproject')),
            ],
            options={
                'db_table': 'opex_project_settings',
            },
        ),
        migrations.DeleteModel(
            name='OpexNonEssentialFactor',
        ),
        migrations.RenameField(
            model_name='materialcosts',
            old_name='price',
            new_name='buying_price',
        ),
        migrations.RemoveField(
            model_name='materialcosts',
            name='material_price',
        ),
        migrations.RemoveField(
            model_name='opexauxiliatefactor',
            name='capex_source',
        ),
        migrations.RemoveField(
            model_name='opexauxiliatefactor',
            name='construction_period',
        ),
        migrations.RemoveField(
            model_name='opexauxiliatefactor',
            name='crm_calculated',
        ),
        migrations.RemoveField(
            model_name='opexauxiliatefactor',
            name='project_life',
        ),
        migrations.RemoveField(
            model_name='opexauxiliatefactor',
            name='revenue_calculated',
        ),
        migrations.RemoveField(
            model_name='opexauxiliatefactor',
            name='salvage_calculated',
        ),
        migrations.AddField(
            model_name='materialcosts',
            name='buying_unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyed_materials', to='capex.equipmentunity'),
        ),
        migrations.AddField(
            model_name='opex',
            name='revenue',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='opex',
            name='salvage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='opex',
            name='working_capital',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='materialcosts',
            name='flow_unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capex.equipmentunity'),
        ),
        migrations.AlterField(
            model_name='opex',
            name='col',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='com',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='crm',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='cut',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='cwt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='depreciation',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='direct_costs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='fci',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='fixed_costs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='opex',
            name='general_expenses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
