# Generated by Django 3.2.8 on 2022-03-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0008_auto_20220301_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcosts',
            old_name='buying_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='materialcosts',
            old_name='buying_unity',
            new_name='unity',
        ),
    ]
