# Generated by Django 3.2.8 on 2022-03-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0003_auto_20220301_1449'),
        ('opex', '0009_auto_20220301_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsutilitiesconstant',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capex.capexproject'),
        ),
    ]
