# Generated by Django 3.2.8 on 2022-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0010_equipmentsutilitiesconstant_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opexprojectsettings',
            name='construction_period',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='opexprojectsettings',
            name='project_life',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
