# Generated by Django 3.2.8 on 2022-03-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0011_auto_20220301_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opex',
            old_name='fci',
            new_name='fcil',
        ),
    ]
