# Generated by Django 3.2.8 on 2022-03-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0003_auto_20220301_1449'),
        ('opex', '0012_rename_fci_opex_fcil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentsUtilitiesConstant',
            new_name='ProjectUtilitiesConstant',
        ),
    ]
