# Generated by Django 3.2.8 on 2022-03-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0013_rename_equipmentsutilitiesconstant_projectutilitiesconstant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectutilitiesconstant',
            old_name='cost',
            new_name='value',
        ),
    ]
