# Generated by Django 3.2.8 on 2022-03-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0015_projectutilitiesconstant_aka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentsutilitiessetting',
            old_name='purchased_factor',
            new_name='equipment',
        ),
        migrations.AddField(
            model_name='equipmentsutilitiessetting',
            name='efficiency',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
