# Generated by Django 3.2.8 on 2022-03-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0016_auto_20220302_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentsutilitiessetting',
            name='classification',
        ),
        migrations.AddField(
            model_name='equipmentsutilitiessetting',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opex.projectutilitiesconstant'),
        ),
    ]
