# Generated by Django 3.2.8 on 2022-03-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0017_auto_20220302_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentsutilitiessetting',
            old_name='cost',
            new_name='annual_cost',
        ),
    ]
