# Generated by Django 3.2.8 on 2022-03-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0018_rename_cost_equipmentsutilitiessetting_annual_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsutilitiessetting',
            name='utility_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
