# Generated by Django 3.2.8 on 2022-03-03 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0004_equipment_utility_form'),
        ('opex', '0019_equipmentsutilitiessetting_utility_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcosts',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capex.capexproject'),
        ),
    ]
