# Generated by Django 3.2.8 on 2022-02-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapexProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.IntegerField(default=100)),
                ('cepci', models.FloatField(default=601.8)),
                ('year', models.IntegerField(default=2017)),
                ('purchased_equip_cost', models.FloatField(default=0.0)),
                ('baremodule_cost', models.FloatField(default=0.0)),
                ('base_equipment_cost', models.FloatField(default=0.0)),
                ('base_baremodule_cost', models.FloatField(default=0.0)),
                ('total_module_cost', models.FloatField(default=0.0)),
                ('total_grassroot_cost', models.FloatField(default=0.0)),
                ('total_equipment_cost', models.FloatField(default=0.0)),
                ('total_langfactor', models.FloatField(default=0.0)),
                ('lang_factor', models.FloatField(default=4.74)),
            ],
            options={
                'db_table': 'capex_project',
            },
        ),
        migrations.CreateModel(
            name='Cepci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', models.FloatField()),
                ('ano', models.IntegerField()),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media_cepci_anual',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=300, null=True)),
                ('symbol', models.CharField(max_length=300, null=True)),
                ('unity', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'dimension',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.dimension')),
            ],
            options={
                'db_table': 'capex_equipment',
            },
        ),
        migrations.CreateModel(
            name='PurchasedFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('k1', models.FloatField(null=True)),
                ('k2', models.FloatField(null=True)),
                ('k3', models.FloatField(null=True)),
                ('max_dimension', models.FloatField(null=True)),
                ('min_dimension', models.FloatField(null=True)),
                ('fixed_value', models.FloatField(null=True)),
                ('reference_year', models.IntegerField(blank=True, null=True)),
                ('cepci', models.FloatField(blank=True, null=True)),
                ('is_reference', models.BooleanField(blank=True, default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.equipment')),
            ],
            options={
                'db_table': 'capex_purchase_factor',
            },
        ),
        migrations.CreateModel(
            name='PressureFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.FloatField(null=True)),
                ('c2', models.FloatField(null=True)),
                ('c3', models.FloatField(null=True)),
                ('pressure_min', models.FloatField(null=True)),
                ('pressure_max', models.FloatField(null=True)),
                ('condition', models.CharField(max_length=300, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.purchasedfactor')),
            ],
            options={
                'db_table': 'capex_pressure_factor',
            },
        ),
        migrations.CreateModel(
            name='MaterialFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.FloatField(null=True)),
                ('b2', models.FloatField(null=True)),
                ('fm', models.FloatField(null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('condition', models.CharField(blank=True, max_length=300, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.purchasedfactor')),
            ],
            options={
                'db_table': 'capex_material_factor',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity', models.CharField(max_length=300, null=True)),
                ('unity_math', models.CharField(max_length=300, null=True)),
                ('convert_factor', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.dimension')),
            ],
            options={
                'db_table': 'equipment_unity',
            },
        ),
        migrations.CreateModel(
            name='EquipmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spares', models.IntegerField(blank=True, default=0)),
                ('specification', models.FloatField(blank=True, default=0)),
                ('pressure', models.FloatField(blank=True, default=0)),
                ('equipment_code', models.CharField(max_length=30, null=True)),
                ('purchased_equip_cost', models.FloatField(null=True)),
                ('baremodule_cost', models.FloatField(null=True)),
                ('base_equipment_cost', models.FloatField(null=True)),
                ('base_baremodule_cost', models.FloatField(null=True)),
                ('cepci', models.FloatField(default=4.74)),
                ('year', models.FloatField(default=2007)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.equipment')),
                ('preference_unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capex.equipmentunity')),
                ('pressureunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_equipment', to='capex.equipmentunity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.capexproject')),
                ('purchased_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.purchasedfactor')),
            ],
            options={
                'db_table': 'capex_equipment_project',
            },
        ),
        migrations.CreateModel(
            name='ComplementConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant', models.CharField(max_length=300, null=True)),
                ('value', models.FloatField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.purchasedfactor')),
            ],
            options={
                'db_table': 'capex_complement_constants',
            },
        ),
        migrations.CreateModel(
            name='BareModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbm', models.FloatField(null=True)),
                ('calculated', models.BooleanField(null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capex.purchasedfactor')),
            ],
            options={
                'db_table': 'capex_baremodule',
            },
        ),
    ]
