# Generated by Django 3.2.8 on 2022-03-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capexproject',
            name='inputed_capex',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='capexproject',
            name='inputed_crm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='capexproject',
            name='inputed_revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='capexproject',
            name='inputed_salvage',
            field=models.FloatField(default=0.0),
        ),
    ]
