# Generated by Django 3.2.8 on 2022-03-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0002_auto_20220228_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capexproject',
            name='inputed_capex',
        ),
        migrations.RemoveField(
            model_name='capexproject',
            name='inputed_crm',
        ),
        migrations.RemoveField(
            model_name='capexproject',
            name='inputed_revenue',
        ),
        migrations.RemoveField(
            model_name='capexproject',
            name='inputed_salvage',
        ),
    ]
