# Generated by Django 3.2.8 on 2022-03-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex', '0003_auto_20220301_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='utility_form',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
