# Generated by Django 3.2.8 on 2021-11-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=300, null=True)),
                ('symbol', models.CharField(max_length=300, null=True)),
                ('unity', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'dimension',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.dimension')),
            ],
            options={
                'db_table': 'turton_equipment',
            },
        ),
        migrations.CreateModel(
            name='PurchasedFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('k1', models.FloatField(null=True)),
                ('k2', models.FloatField(null=True)),
                ('k3', models.FloatField(null=True)),
                ('max_dimension', models.FloatField(null=True)),
                ('min_dimension', models.FloatField(null=True)),
                ('fixed_value', models.FloatField(null=True)),
                ('reference_year', models.IntegerField(blank=True, null=True)),
                ('cepci', models.FloatField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.equipment')),
            ],
            options={
                'db_table': 'turton_purchase_factor',
            },
        ),
        migrations.CreateModel(
            name='PressureFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.FloatField(null=True)),
                ('c2', models.FloatField(null=True)),
                ('c3', models.FloatField(null=True)),
                ('pressure_min', models.FloatField(null=True)),
                ('pressure_max', models.FloatField(null=True)),
                ('condition', models.CharField(max_length=300, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.purchasedfactor')),
            ],
            options={
                'db_table': 'turton_pressure_factor',
            },
        ),
        migrations.CreateModel(
            name='MaterialFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.FloatField(null=True)),
                ('b2', models.FloatField(null=True)),
                ('fm', models.FloatField(null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('condition', models.CharField(max_length=300, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.purchasedfactor')),
            ],
            options={
                'db_table': 'turton_material_factor',
            },
        ),
        migrations.CreateModel(
            name='ComplementConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant', models.CharField(max_length=300, null=True)),
                ('value', models.FloatField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.purchasedfactor')),
            ],
            options={
                'db_table': 'turton_complement_constants',
            },
        ),
        migrations.CreateModel(
            name='BareModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbm', models.FloatField(null=True)),
                ('calculated', models.BooleanField(null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.purchasedfactor')),
            ],
            options={
                'db_table': 'turton_baremodule',
            },
        ),
    ]
