# Generated by Django 3.2.8 on 2021-11-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtonapp', '0002_baremodule_is_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedfactor',
            name='is_reference',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
