# Generated by Django 3.2.8 on 2021-11-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turtonapp', '0003_purchasedfactor_is_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baremodule',
            name='is_reference',
        ),
    ]
