# Generated by Django 3.2.8 on 2021-11-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turtonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity', models.CharField(max_length=300, null=True)),
                ('unity_math', models.CharField(max_length=300, null=True)),
                ('convert_factor', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.dimension')),
            ],
            options={
                'db_table': 'equipment_unity',
            },
        ),
    ]
