# Generated by Django 3.2.8 on 2022-02-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turtonapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapexProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.IntegerField(default=100)),
                ('cepci', models.FloatField(default=601.8)),
                ('year', models.IntegerField(default=2017)),
                ('purchased_equip_cost', models.FloatField(default=0.0)),
                ('baremodule_cost', models.FloatField(default=0.0)),
                ('base_equipment_cost', models.FloatField(default=0.0)),
                ('base_baremodule_cost', models.FloatField(default=0.0)),
                ('total_module_cost', models.FloatField(default=0.0)),
                ('total_grassroot_cost', models.FloatField(default=0.0)),
                ('total_equipment_cost', models.FloatField(default=0.0)),
                ('total_langfactor', models.FloatField(default=0.0)),
                ('lang_factor', models.FloatField(default=4.74)),
            ],
            options={
                'db_table': 'capex_project',
            },
        ),
        migrations.CreateModel(
            name='Cepci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', models.FloatField()),
                ('ano', models.IntegerField()),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media_cepci_anual',
            },
        ),
        migrations.CreateModel(
            name='HistoricoFluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'fluxo_caixa_empresa',
            },
        ),
        migrations.CreateModel(
            name='EquipmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spares', models.IntegerField(blank=True, default=0)),
                ('specification', models.FloatField(blank=True, default=0)),
                ('pressure', models.FloatField(blank=True, default=0)),
                ('equipment_code', models.CharField(max_length=30, null=True)),
                ('purchased_equip_cost', models.FloatField(null=True)),
                ('baremodule_cost', models.FloatField(null=True)),
                ('base_equipment_cost', models.FloatField(null=True)),
                ('base_baremodule_cost', models.FloatField(null=True)),
                ('cepci', models.FloatField(default=4.74)),
                ('year', models.FloatField(default=2007)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.equipment')),
                ('preference_unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turtonapp.equipmentunity')),
                ('pressureunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_equipment', to='turtonapp.equipmentunity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capitalcost.capexproject')),
                ('purchased_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtonapp.purchasedfactor')),
            ],
            options={
                'db_table': 'capex_equipment_project',
            },
        ),
    ]
