# Generated by Django 3.2.8 on 2021-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentproject',
            name='spares',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
