# Generated by Django 3.2.8 on 2021-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcost', '0002_equipmentproject_spares'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentproject',
            name='specification',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
