# Generated by Django 3.2.8 on 2021-11-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitalcost', '0003_equipmentproject_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentproject',
            name='pressure',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
